name: bfban
description: bfban
version: 1.0.0+1
environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  # 请求模块 https://pub.dev/packages/dio
  dio: 3.0.9

  # cookie管理器
  #  cookie_jar: 1.0.0
  dio_cookie_manager: 1.0.0

  # 状态管理
  scoped_model: 1.0.1

  # 路由管理
  fluro: 1.6.3

  # 包信息
  package_info: ^0.4.0+1

  # html https://pub.dev/packages/flutter_html
  flutter_html: ^1.0.2

  # svg渲染模块 https://pub.dev/packages/flutter_svg
  flutter_svg: ^0.18.1

  # 数据储存 https://pub.flutter-io.cn/packages/shared_preferences
  shared_preferences: ^0.5.3+4

  # 链接 https://pub.flutter-io.cn/packages/url_launcher
  url_launcher: 5.5.0

  video_player: any

  # 游览器 https://pub.flutter-io.cn/packages/webview_flutter
  webview_flutter: ^0.3.22+1

  # 图片查看 https://pub.flutter-io.cn/packages/photo_view
  photo_view: 0.9.2

  # 权限 https://pub.flutter-io.cn/packages/permission_handler
  permission_handler: 5.0.1

  # 分享 https://pub.flutter-io.cn/packages/flutter_share
  flutter_share: 1.0.2+1

  # link https://pub.flutter-io.cn/packages/uni_links
  uni_links: 0.4.0

  # 本地通知 https://pub.flutter-io.cn/packages/flutter_local_notifications
  flutter_local_notifications: 1.4.4+2

  # https://pub.flutter-io.cn/packages/image_picker
  image_picker: 0.6.7+4

  # https://pub.flutter-io.cn/packages/rich_edit
  chewie: 0.9.10
  rich_edit: 0.1.1

  # uuid https://github.com/Daegalus/dart-uuid
  uuid: 2.2.0

  # 图片保存
  image_gallery_saver: ^1.2.2

  # https://pub.dev/packages/sentry
  sentry: 3.0.1

  flutter_plugin_elui:
    path: ../../flutter-elui-plugin

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/video/
    - assets/images/
    - assets/images/edit/