name: bfban
description: bfban.com
publish_to: 'none'
version: '0.2.1-beta'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  flutter_math_fork: ^0.6.1
  cupertino_icons: ^1.0.2
  # 请求模块 https://pub.dev/packages/dio
  dio: ^4.0.4

  # cookie管理器 https://pub.dev/packages/dio_cookie_manager
  dio_cookie_manager: ^2.0.0

  # 状态管理 https://pub.dev/packages/provider
  provider: ^6.0.2

  # 路由管理 https://pub.dev/packages/fluro
  fluro: ^2.0.3

  # 包信息  https://pub.dev/packages/package_info_plus
  package_info_plus: ^1.3.0

  # html https://pub.dev/packages/flutter_html
  flutter_html: any

  # svg渲染模块 https://pub.dev/packages/flutter_svg
  flutter_svg: any

  # 数据储存 https://pub.flutter-io.cn/packages/shared_preferences
  shared_preferences: ^2.0.6

  # 数据储存监听 https://pub.flutter-io.cn/packages/streaming_shared_preferences
  streaming_shared_preferences: ^2.0.0

  # 链接 https://pub.flutter-io.cn/packages/url_launcher
  url_launcher: ^6.0.18

  # 唤醒 https://pub.flutter-io.cn/packages/wakelock
  wakelock: ^0.6.1

  # 游览器 https://pub.flutter-io.cn/packages/webview_flutter
  webview_flutter: ^2.8.0

  # 图片查看 https://pub.flutter-io.cn/packages/photo_view
  photo_view: ^0.13.0

  # 权限 https://pub.flutter-io.cn/packages/permission_handler
  permission_handler: ^8.3.0

  # 分享 https://pub.flutter-io.cn/packages/flutter_share
  flutter_share: ^2.0.0

  # link https://pub.flutter-io.cn/packages/uni_links
  uni_links: ^0.5.1

  # QR https://pub.flutter-io.cn/packages/flutter_barcode_sdk
  flutter_barcode_sdk: ^1.2.2
  camera: ^0.10.0+3

  # 本地通知x消息 https://pub.flutter-io.cn/packages/flutter_local_notifications
  flutter_local_notifications: ^9.2.0

  # 图像选择器 https://pub.flutter-io.cn/packages/image_picker
  image_picker: ^0.8.1

  # https://pub.flutter-io.cn/packages/minimal_html_editor
  minimal_html_editor: ^1.1.2+1

  # uuid https://github.com/Daegalus/dart-uuid
  uuid: ^3.0.4

  # 多国语言 https://github.com/Daegalus/flutter_translate
  # https://www.unicode.org/reports/tr35/#Unicode_language_identifier
  flutter_translate: ^3.0.1
  flutter_i18n: ^0.32.4

  # 图片保存
  image_gallery_saver: ^1.2.2

  # https://pub.dev/packages/sentry
  sentry: 6.2.2

  # UI库
  flutter_elui_plugin:
    path: ../flutter_elui_plugin

  # 视频 https://pub.flutter-io.cn/packages/video_player
  video_player: ^2.1.1

  animations: ^2.0.0

  # 极光 https://pub.flutter-io.cn/packages/jpush_flutter
  # 需要配置android/ios目录
  jpush_flutter: ^2.2.2

  # 广告
#  google_mobile_ads: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  # 启动屏幕 https://pub.flutter-io.cn/packages/flutter_native_splash
  flutter_native_splash: ^1.3.3

flutter_native_splash:
  color: "#111b2b"
  branding: assets/splash/ic_launcher.png
  image: assets/splash/splash_center_logo.png
  branding_mode: center
  android_gravity: center
  fullscreen: true
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lang/
    - assets/lang/en/
    - assets/lang/zh/
    - assets/video/
    - assets/images/
    - assets/images/games/bf1/
    - assets/images/games/bf6/
    - assets/images/games/bfv/
    - assets/splash/